"""Setting the DOCUMENT's language from the builder, through a real browser.

WHY THIS IS A BROWSER TEST AND NOT A REQUEST TEST

    Every layer beneath this control has been bilingual since phase 7, and
    each has its own gate. What was missing was the control itself, and all of
    it lives in the browser: the form is generated by builder.js, the level
    dropdowns are re-offered client-side from a table the page ships, the
    remap rewrites `data` in memory, and the whole thing reaches disk only via
    autosave. A `test_client()` runs none of that - which is precisely how
    `lang` came to be settable by hand-editing `data/resume.json` and no other
    way, in a schema-valid, fully-tested app.

    `tests/test_document_language.py` holds the request-level and static half
    (the payload, the vocabularies, the invariant the remap rests on). This
    file holds the four things only a browser can answer:

      1. the switch actually re-renders the document right-to-left;
      2. the offer to translate the stored level words is an OFFER - declining
         leaves a working résumé, in a state the user chose;
      3. the translation is lossless, so the switch is reversible;
      4. the interface language is still not involved.

    (2) is the one worth having. Rewriting user content is the kind of thing a
    dialog makes look consensual while the code applies it either way.
"""
from __future__ import annotations

import pytest
from playwright.sync_api import expect

from app.i18n import COOKIE
from app.labels import LANGUAGE_LEVELS, SKILL_LEVELS, translation_for

pytestmark = pytest.mark.e2e

#: The sample's first skill, and what it becomes. Derived rather than spelled
#: out, so reordering the vocabulary fails the invariant test in the fast loop
#: instead of quietly changing what this file means.
EN_TOP_SKILL = SKILL_LEVELS["en"][0]                     # "Expert"
AR_TOP_SKILL = SKILL_LEVELS["ar"][0]
EN_TOP_LANGUAGE = LANGUAGE_LEVELS["en"][0]               # "Native"
AR_TOP_LANGUAGE = LANGUAGE_LEVELS["ar"][0]


def _preview(page):
    return page.frame_locator("#preview-frame").locator(".tpl")


def _stored(page, live_server) -> dict:
    return page.request.get(live_server.url + "/api/resume").json()["resume"]


def _switch_language(page, to: str, *, translate: bool):
    """Pick a language and answer the remap offer.

    Playwright auto-dismisses dialogs when nothing is listening, so the
    `translate=False` path would pass even if the handler never asked. Both
    answers are given explicitly, and the returned list proves the question
    was actually put."""
    saw: list[str] = []

    def _answer(dialog):
        saw.append(dialog.message)
        if translate:
            dialog.accept()
        else:
            dialog.dismiss()

    page.once("dialog", _answer)
    page.select_option("#f_lang", to)
    expect(page.locator("#save-state")).to_have_text("Saved")
    return saw


# ------------------------------------------------------- the control exists

def test_an_english_resume_shows_english_and_reads_left_to_right(page, live_server):
    """The seeded sample has no `lang` key at all. Absent means English - the
    degrade path that kept every pre-bilingual résumé working - so the control
    has to show `English`, not a blank."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")

    expect(page.locator("#f_lang")).to_have_value("en")
    assert page.frame_locator("#preview-frame").locator("html").get_attribute("dir") == "ltr"
    assert "lang" not in _stored(page, live_server), "nothing written before the user picks"


# ------------------------------------------------------------ the switch

def test_switching_to_arabic_turns_the_document_round(page, live_server):
    """`resume.lang` drives `dir`, the section headings and the font sheet.

    Asserted on the iframe's own <html>: the shell has no cookie here and is
    still English, so a test that looked at the outer page would pass while
    the résumé rendered left-to-right - which is the exact bug this control
    exists to make unreachable."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")

    _switch_language(page, "ar", translate=True)

    frame = page.frame_locator("#preview-frame")
    assert frame.locator("html").get_attribute("dir") == "rtl"
    assert frame.locator("html").get_attribute("lang") == "ar"
    # The default template's own headings, translated - not just the direction
    # flipping under English text.
    for msgid in ("Experience", "Education"):
        expect(frame.locator(".tpl")).to_contain_text(translation_for(msgid))

    assert _stored(page, live_server)["lang"] == "ar"
    # ...and the interface around it is untouched
    assert page.locator("html").get_attribute("dir") == "ltr"
    expect(page.locator("#save-state")).to_have_text("Saved")


def test_the_dropdowns_re_offer_the_new_language_without_a_reload(page, live_server):
    """The level words are STORED and printed, so they follow the document.
    After the switch the form has to offer the other vocabulary immediately -
    the page ships both lists for exactly this."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    page.click('details.sec[data-sid="skills"] > summary')
    offered_before = page.locator("#f_skills_0_level option").all_text_contents()
    assert [o for o in offered_before if o] == SKILL_LEVELS["en"]

    _switch_language(page, "ar", translate=True)

    page.click('details.sec[data-sid="skills"] > summary')
    offered = page.locator("#f_skills_0_level option").all_text_contents()
    assert [o for o in offered if o] == SKILL_LEVELS["ar"]


# --------------------------------------------------- the remap is an offer

def test_accepting_the_offer_translates_the_words_already_chosen(page, live_server):
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    before = _stored(page, live_server)
    assert before["skills"][0]["level"] == EN_TOP_SKILL

    asked = _switch_language(page, "ar", translate=True)
    assert asked, "the user was never asked"

    after = _stored(page, live_server)
    assert after["skills"][0]["level"] == AR_TOP_SKILL
    assert after["languages"][0]["level"] == AR_TOP_LANGUAGE
    # the skill NAMES are the user's own text and are not translated
    assert after["skills"][0]["name"] == before["skills"][0]["name"]


def test_declining_the_offer_leaves_the_words_alone(page, live_server):
    """Declining has to produce a working résumé, not a half-applied one.

    `LEVEL_DOTS` maps both vocabularies, so an English `Expert` in an Arabic
    document still draws five dots - it just reads in Latin. That is a legible
    state for a bilingual user to choose, and it is why the remap is offered
    rather than done."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")

    asked = _switch_language(page, "ar", translate=False)
    assert asked, "the user was never asked"

    after = _stored(page, live_server)
    assert after["lang"] == "ar", "the language change itself is not conditional"
    assert after["skills"][0]["level"] == EN_TOP_SKILL
    assert after["languages"][0]["level"] == EN_TOP_LANGUAGE
    # and it is still on the page as real text, beside its dots
    expect(_preview(page)).to_contain_text(EN_TOP_SKILL)


def test_the_switch_is_reversible(page, live_server):
    """en -> ar -> en returns the words it started with. The remap is
    positional, so a ragged or reordered vocabulary would show up here as a
    silently regraded skill."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    before = _stored(page, live_server)

    _switch_language(page, "ar", translate=True)
    _switch_language(page, "en", translate=True)

    after = _stored(page, live_server)
    assert after["lang"] == "en"
    assert [s["level"] for s in after["skills"]] == [s["level"] for s in before["skills"]]
    assert ([x["level"] for x in after["languages"]]
            == [x["level"] for x in before["languages"]])
    assert page.frame_locator("#preview-frame").locator("html").get_attribute("dir") == "ltr"


def test_the_choice_survives_a_reload(page, live_server):
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    _switch_language(page, "ar", translate=True)

    page.reload()
    expect(page.locator("#f_lang")).to_have_value("ar")
    assert page.frame_locator("#preview-frame").locator("html").get_attribute("dir") == "rtl"


# ------------------------------------------- the two languages stay apart

def test_an_arabic_interface_does_not_relabel_an_english_document(page, live_server):
    """THE SHARP CASE, and the reason this control reads the file rather than
    the cookie: a bilingual user applying to an English-speaking employer from
    an Arabic UI. Wiring the control to `ui_lang` would look right in every
    case where the two agree, and would put an Arabic level word into an
    English résumé."""
    page.context.add_cookies([{"name": COOKIE, "value": "ar", "url": live_server.url}])
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")

    assert page.locator("html").get_attribute("dir") == "rtl"      # the shell
    expect(page.locator("#f_lang")).to_have_value("en")            # the document
    assert page.frame_locator("#preview-frame").locator("html").get_attribute("dir") == "ltr"

    page.click('details.sec[data-sid="skills"] > summary')
    offered = page.locator("#f_skills_0_level option").all_text_contents()
    assert [o for o in offered if o] == SKILL_LEVELS["en"]


def test_setting_the_document_to_arabic_does_not_move_the_interface(page, live_server):
    """The mirror image: the reader's language is a cookie the builder must
    never write."""
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    _switch_language(page, "ar", translate=True)

    assert page.locator("html").get_attribute("lang") == "en"
    assert page.locator("html").get_attribute("dir") == "ltr"
    assert not [c for c in page.context.cookies() if c["name"] == COOKIE]
    expect(page.locator('label[for="f_lang"]')).to_have_text("Résumé language")
