"""Switching language turns the whole thing round — app and document together.

WHAT THIS FILE USED TO BE

    `test_language_control.py`, covering a `Résumé language` select in Basics
    that gave each résumé a language of its own, independent of the interface.
    The independence was real and deliberate: a bilingual applicant writing an
    English CV from an Arabic UI. In front of an actual user, on 2026-09-22,
    the control turned out to restate a choice already made in the header, and
    it was removed.

    What survives is everything underneath it, which was never about the
    control: a switch has to turn the document round, re-offer the level
    vocabulary, translate the words already stored, and be reversible. Those
    are the tests here, driven through the header switch instead.

    What is gone with it is one case, stated plainly: an Arabic interface
    around an English résumé can no longer be expressed.

WHY THIS IS A BROWSER TEST

    All of it lives in the browser. The form is generated by builder.js, the
    level dropdowns are re-offered client-side from a table the page ships,
    and the adoption rewrites `data` in memory on boot. A `test_client()` runs
    none of it — which is how the document language came to be settable by
    hand-editing a JSON file and no other way, in a fully-tested app.

    `tests/test_document_language.py` holds the request-level and static half.
"""
from __future__ import annotations

import pytest
from playwright.sync_api import expect

from app.i18n import COOKIE
from app.labels import LANGUAGE_LEVELS, SKILL_LEVELS, translation_for

pytestmark = pytest.mark.e2e

#: Derived, not spelled out, so reordering a vocabulary fails the invariant
#: test in the fast loop instead of quietly changing what this file means.
EN_TOP_SKILL = SKILL_LEVELS["en"][0]                     # "Expert"
AR_TOP_SKILL = SKILL_LEVELS["ar"][0]
EN_TOP_LANGUAGE = LANGUAGE_LEVELS["en"][0]               # "Native"
AR_TOP_LANGUAGE = LANGUAGE_LEVELS["ar"][0]


def _preview(page):
    return page.frame_locator("#preview-frame").locator(".tpl")


def _doc(page):
    return page.frame_locator("#preview-frame").locator("html")


def _switch(page, live_server, to: str):
    """Choose a language the only way there is to now.

    The builder blanks the site header to give the preview the screen, so the
    switch is the same navigation the header link performs — not a shortcut
    around the UI, but the identical request with the same `next`.
    """
    page.goto(f"{live_server.url}/lang/{to}?next=/builder")
    expect(_preview(page)).to_be_visible()


# ------------------------------------------------------------- the switch

def test_english_is_what_a_visitor_who_chose_nothing_gets(page, live_server):
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")
    assert _doc(page).get_attribute("dir") == "ltr"


def test_switching_to_arabic_turns_the_document_round(page, live_server):
    """`lang` drives `dir`, the section headings and the font sheet.

    Asserted on the IFRAME's own <html>: a test that looked at the outer page
    would pass on the shell alone while the résumé inside it still read
    left-to-right — which is the exact bug reported from production.
    """
    page.goto(live_server.url + "/builder")
    expect(_preview(page)).to_contain_text("Ashworth")

    _switch(page, live_server, "ar")

    assert _doc(page).get_attribute("dir") == "rtl"
    assert _doc(page).get_attribute("lang") == "ar"
    # The template's own headings, translated — not the direction flipping
    # under English text.
    for msgid in ("Experience", "Education"):
        expect(_preview(page)).to_contain_text(translation_for(msgid))


def test_the_dropdowns_re_offer_the_new_language(page, live_server):
    """Level words are STORED and printed, so they follow the document. After
    the switch the form has to offer the other vocabulary."""
    page.goto(live_server.url + "/builder")
    page.click('details.sec[data-sid="skills"] > summary')
    offered = page.locator("#f_skills_0_level option").all_text_contents()
    assert [o for o in offered if o] == SKILL_LEVELS["en"]

    _switch(page, live_server, "ar")

    page.click('details.sec[data-sid="skills"] > summary')
    offered = page.locator("#f_skills_0_level option").all_text_contents()
    assert [o for o in offered if o] == SKILL_LEVELS["ar"]


def test_the_words_already_chosen_are_translated(page, live_server):
    """The remap, which used to be a `window.confirm` the user answered.

    It runs on boot now and asks nothing: a dialog is reasonable when someone
    has just picked something, and an ambush on page load. It is only allowed
    to be silent because it is lossless — see the reversibility test below.
    """
    page.goto(live_server.url + "/builder")
    page.click('details.sec[data-sid="skills"] > summary')
    expect(page.locator("#f_skills_0_level")).to_have_value(EN_TOP_SKILL)

    _switch(page, live_server, "ar")

    page.click('details.sec[data-sid="skills"] > summary')
    expect(page.locator("#f_skills_0_level")).to_have_value(AR_TOP_SKILL)
    page.click('details.sec[data-sid="languages"] > summary')
    expect(page.locator("#f_languages_0_level")).to_have_value(AR_TOP_LANGUAGE)


def test_the_switch_is_reversible(page, live_server):
    """What makes translating without asking acceptable: switch back and the
    words come back, because position is the translation in both directions."""
    page.goto(live_server.url + "/builder")
    _switch(page, live_server, "ar")
    _switch(page, live_server, "en")

    page.click('details.sec[data-sid="skills"] > summary')
    expect(page.locator("#f_skills_0_level")).to_have_value(EN_TOP_SKILL)
    page.click('details.sec[data-sid="languages"] > summary')
    expect(page.locator("#f_languages_0_level")).to_have_value(EN_TOP_LANGUAGE)
    assert _doc(page).get_attribute("dir") == "ltr"


def test_the_choice_survives_a_reload(page, live_server):
    _switch(page, live_server, "ar")
    page.reload()
    assert _doc(page).get_attribute("dir") == "rtl"


# ------------------------------------- what the user typed is NOT touched

def test_the_text_you_wrote_is_left_exactly_as_written(page, live_server):
    """The remap moves LEVEL words, which come from our own vocabulary. Every
    other字 on the page is the user's and must survive the switch byte for
    byte — an Arabic CV naming English employers is an ordinary document."""
    mine = "Halden & Row"
    page.goto(live_server.url + "/builder")
    page.fill("#f_name", mine)
    expect(page.locator("#save-state")).to_have_text("Saved")

    _switch(page, live_server, "ar")

    expect(page.locator("#f_name")).to_have_value(mine)
    expect(_preview(page)).to_contain_text(mine)


def test_the_builder_never_writes_the_language_cookie(page, live_server):
    """The cookie is set by `/lang/<code>` and by nothing else. A second
    writer is how a setting ends up disagreeing with itself."""
    page.goto(live_server.url + "/builder")
    page.fill("#f_name", "Anyone")
    expect(page.locator("#save-state")).to_have_text("Saved")
    assert not [c for c in page.context.cookies() if c["name"] == COOKIE]
