"""HTML rendering: resume data + template key -> the 850x1100 canvas, and a
full standalone HTML document wrapping it (used by the preview iframe and the
PDF exporter).

Template keys are "<category>-<block>" (see app/registry.py). The Jinja file
for a key is app/templates/resumes/<category>/<block>.j2 and emits ONLY the
`.tpl` canvas div. `document_html()` wraps that fragment with the font partial
and print CSS so preview and PDF share one code path.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape
from markupsafe import Markup

from . import registry
from .labels import join_labels, reset_lang, set_lang, t
from .schema import dir_of, lang_of, normalize, typography_of
from .typography.render import document_blocks

_TPL_DIR = Path(__file__).resolve().parent / "templates" / "resumes"


@lru_cache(maxsize=1)
def _env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(_TPL_DIR)),
        autoescape=select_autoescape(["j2", "html"]),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # Every fixed label in the 49 templates renders through t(). It resolves
    # the language from a ContextVar rather than the Jinja context, because
    # the templates import _macros.j2 WITHOUT context, so a pass_context
    # version would silently return English inside any macro. See app/labels.py.
    env.globals["t"] = t
    env.globals["join_labels"] = join_labels
    env.filters["br_join"] = _br_join
    return env


def _br_join(items) -> Markup:
    """Join user-supplied strings with a line break, escaping each one.

    Thirteen templates used to write `{{ items | join("<br>") | safe }}`, which
    marked the WHOLE joined string safe -- the user's own field values along
    with the separator. An email, skill name or tool containing markup then
    rendered as live HTML: in the builder preview, in the template drawer, and
    inside the headless Chromium the PDF exporter drives. Harmless while the
    app was single-user and local; stored XSS the moment it is not.

    `Markup.join` is the fix rather than a manual escape: it escapes every
    non-Markup item and keeps the separator as real markup, which is the
    behaviour those call sites always wanted. A value that is ALREADY Markup
    (a catalogue string through `t()`) passes through untouched, so nothing
    double-escapes. See app/labels.py::_as_html for the same distinction drawn
    from the other side -- our own strings, escaped only as far as text needs.
    """
    return Markup("<br>").join(items)


class UnknownTemplate(ValueError):
    pass


def _template_path(key: str) -> str:
    tpl = registry.get(key)
    if tpl is None:
        raise UnknownTemplate(f"{key!r} is not in the registry")
    if not tpl.ported:
        raise UnknownTemplate(f"{key!r} ({tpl.label}) is catalogued but not ported yet")
    return f"{tpl.category}/{tpl.block}.j2"


def canvas_html(data: dict, template_key: str) -> str:
    """Render just the resume canvas fragment for `template_key`.

    The document language is bound for the duration of the render so the
    templates' t() calls resolve against it, and reset in a `finally`: a
    template that raises must not leave the next render — this thread
    serves many — stuck in the wrong language.
    """
    tpl = _env().get_template(_template_path(template_key))
    token = set_lang(lang_of(data))
    try:
        return tpl.render(r=normalize(data), meta=registry.get(template_key))
    finally:
        reset_lang(token)


_FONT_LINK = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
    "family=Poppins:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700;800"
    "&family=Fraunces:opsz,wght@9..144,500;9..144,700"
    "&family=Montserrat:wght@400;500;600;700;800;900&family=Anton"
    "&family=Archivo+Narrow:wght@400;500;600;700"
    "&family=Archivo:wght@400;600;700;800;900"
    "&family=Source+Sans+3:wght@400;600;700;900"
    "&family=Merriweather:wght@400;700&family=Open+Sans:wght@400;600;700"
    "&family=IBM+Plex+Mono:wght@400;500;600&display=swap\">"
)

_FONTS_DIR = Path(__file__).resolve().parent / "static" / "fonts"

# Self-hosted fonts, generated by tools/fetch_fonts.py. Two forms, because the
# preview and the PDF resolve URLs differently:
#
#   FONT_HEAD  — <link> to /static/fonts/fonts.css. Used by the preview, which
#     is served over HTTP (`/preview`, and an iframe `srcdoc` that inherits the
#     page's base URL), so the browser resolves and caches the files.
#
#   font_head(for_pdf=True) — the same rules with the fonts embedded as data:
#     URIs, inlined into the document. PDF export renders through Playwright's
#     `page.set_content()`, whose base URL is `about:blank`: a "/static/..." URL
#     has nothing to resolve against and fails SILENTLY, Chromium substituting a
#     fallback face with no error. Embedding the bytes removes the lookup
#     entirely — there is nothing left to fail. ~1.35 MB per export, which is a
#     one-off user action, versus the preview's every-keystroke re-render.
#
# _FONT_LINK (the Google CDN) is kept only as the documented fallback if
# static/fonts/ is ever missing.
FONT_HEAD = '<link rel="stylesheet" href="/static/fonts/fonts.css">'


# Arabic coverage, generated by tools/fetch_fonts_ar.py. Those rules are
# declared under the LATIN family names and confined by unicode-range to Arabic
# codepoints, so loading this stylesheet adds Arabic glyphs to the families the
# templates already ask for without touching a single Latin glyph.
#
# It loads ONLY for lang="ar". Not for safety — the unicode-range already
# guarantees that — but for weight: the inline copy is ~2.1 MB, and an English
# export has no reason to carry it.
FONT_HEAD_AR = '<link rel="stylesheet" href="/static/fonts/fonts_ar.css">'


def font_head(*, for_pdf: bool = False, lang: str = "en") -> str:
    if not for_pdf:
        return FONT_HEAD + (FONT_HEAD_AR if lang == "ar" else "")
    inline = _FONTS_DIR / "fonts_inline.css"
    if not inline.exists():  # pragma: no cover - only if fetch_fonts never ran
        return _FONT_LINK
    css = inline.read_text(encoding="utf-8")
    if lang == "ar":
        ar = _FONTS_DIR / "fonts_ar_inline.css"
        if ar.exists():  # pragma: no branch - absent only if fetch_fonts_ar never ran
            css += "\n" + ar.read_text(encoding="utf-8")
    return "<style>\n" + css + "\n</style>"


_AUTOFIT_JS = Path(__file__).resolve().parent / "static" / "js" / "autofit.js"


@lru_cache(maxsize=1)
def autofit_script() -> str:
    """The auto-fit engine, INLINED into the document.

    Inlined rather than <script src>'d for the same reason the PDF fonts are:
    the PDF path renders through Playwright's `set_content()`, whose base URL is
    about:blank, so `/static/js/autofit.js` would resolve to nothing and fail
    silently — the PDF would then paginate differently from the preview.

    One copy therefore serves all three consumers (preview iframe, PDF export,
    and tools/verify_autofit.py), which is the point: the fit the user approves
    on screen is the fit that gets printed.
    """
    if not _AUTOFIT_JS.exists():  # pragma: no cover - only if the file is deleted
        return ""
    return "<script>\n" + _AUTOFIT_JS.read_text(encoding="utf-8") + "\n</script>"


# Arabic / RTL typography. Emitted by document_html() ONLY when the document
# is RTL, the same shape as the Arabic font sheet: an English document never
# carries these rules at all, so they cannot affect it even by accident.
RTL_TYPOGRAPHY = """<style>
  /* ---- Arabic / RTL typography -------------------------------------------
     Injected ONLY for dir="rtl" (see document_html), so an English document
     never carries these rules at all.

     This block is deliberately SMALLER than the phase-4 plan called for. The
     plan was to kill `letter-spacing` and `text-transform` document-wide under
     RTL, on the premise that "letter-spacing breaks Arabic's cursive joining".
     Measured in Chromium, it does not. Across Archivo, Montserrat, Poppins,
     Anton and Merriweather at letter-spacing:2.5px:

         Arabic, one word  (8 chars) ..... grew 0.00 gaps
         Arabic, two words (14 chars) .... grew 1.00 gaps  (the word space only)
         Latin            (15 chars) ..... grew 15.0 gaps  (every gap)

     Tracking is applied to ZERO gaps inside a joined Arabic run. So the purge
     would have fixed nothing measurable - and it caused real harm: neutralising
     tracking WIDENS text, and all 42 negative-tracking declarations in the
     catalogue are display type (23px-64px mastheads). Removing -1px from
     modern-t10's name tipped it onto a second line, +38.7px, for no benefit.
     `text-transform:uppercase` is likewise a no-op on a script with no case,
     and 23 of those same mastheads carry it deliberately.

     Both purges were therefore dropped rather than shipped. What is left is the
     one thing that measurement DID justify.

     ---- heading rescue ----
     An English section heading carries three cues: size, weight, and
     small-caps-with-tracking. In Arabic the third is worth nothing. A heading
     that leant on it flattens into body text.

     Every section heading in all 49 templates was measured against its own body
     text - possible only because phase 3 made a heading identifiable by its
     catalogue string:

         45 templates .... carried by size (up to 2.6x body), by weight 700-900,
                           or by a rule/fill behind the heading. Left ALONE.
         ats-t13/19/21/23  heading size ~= body (ratio 1.00-1.04), weight 600,
                           no rule, no fill. Only colour survived, and the
                           render confirms they read as body text.

     Those four - and only those four - carry `sec-head` on the heading element.
     The class is inert in LTR: nothing targets it there, and this stylesheet is
     not emitted for LTR at all, which is why the pixel gate does not move.

     Size AND weight: 600 -> 700 alone is too small a step to re-make a heading.
     Lifts the four from ratio 1.00-1.04 to 1.17 - the same ratio as ats-t1,
     which reads correctly. 14.5px read no better and left ats-t23, the
     tightest of the four, with only 10px of the page to spare; 14px leaves
     ~22px. */
  /* ---- the one decoration logical properties cannot mirror ---------------
     modern-t22 hangs a rotated 'RESUME' rail down its edge. Stage 5A moved it
     to inset-inline-start, so its BOX mirrors - but `transform` has no logical
     form: translate(-50%) still moves left, and rotate(-90deg) still turns the
     same way, so the rail landed at x=-388 in RTL. Mirroring a transform means
     negating it, which only a direction-scoped rule can do.

     The rail also had to stop being six separately-kerned Latin letters: the
     template emits a single span for RTL, because Arabic is cursive and six
     isolated glyphs are not a word. The Latin branch is untouched, which is
     why English HTML for this template is unchanged apart from the class. */
  [dir="rtl"] .tpl .vrail {
    transform: translate(50%, -50%) rotate(90deg) !important;
    /* 214px suits six Latin caps; the Arabic term is two words and its
       ascenders/descenders overflow the 215px rail, so it is set smaller. */
    font-size: 140px !important;
    /* The Latin rail uses flex-start because 'RESUME' at 214px nearly fills
       the 1043.5px track. The Arabic term runs ~700px, so it is centred
       along the rail instead of hanging off one end. */
    justify-content: center !important;
  }

  [dir="rtl"] .tpl .sec-head {
    font-size: 14px !important;
    font-weight: 700 !important;
  }

  /* ---- the font policy's CV roles ---------------------------------------
     The user's written policy names three faces for a CV by ROLE:

         Name           Tajawal ExtraBold
         Section title  Cairo Bold
         Body           IBM Plex Sans Arabic, 10-12pt, line-height 1.6

     ARABIC ONLY. This whole stylesheet is emitted by document_html() solely
     for dir="rtl", so an English CV never carries a byte of it. The classes
     it targets are inert in LTR: nothing selects them there. That is the
     standing instruction - the policy is about Arabic type and must not move
     an English template.

     WHY THE ALIAS LAYER COULD NOT DO THIS. Arabic normally reaches the 49
     templates through fonts_ar.css, which declares each Arabic face under a
     LATIN family name and confines it by unicode-range. That layer keys on
     (family, weight), so it can only express "Archivo becomes Tajawal" - not
     "the name becomes Tajawal". Weight is not a usable proxy for role here,
     measured across all 49: Archivo 900 is used at 25px (x30) AND at 12px
     (x25), and Open Sans 700 is 12px in 42 of its uses. Mapping the heavy
     weights to a display face would have put Cairo and Tajawal on bold words
     inside paragraphs in every template. So the roles are marked in the
     markup instead, and named here.

     WHY !important. Every one of the 49 templates sets font-family in an
     INLINE style attribute, which outranks any stylesheet rule. Nothing here
     is !important for emphasis; it is the only declaration that reaches. The
     inline styles carry no !important of their own, so ordinary specificity
     still decides between the three rules below - .tpl .cv-name (0,2,0) beats
     .tpl * (0,1,0), which is what makes the name win over the body default.

     FAMILY ONLY. Size, colour, weight, tracking and layout stay exactly as
     each template set them - that is the template's identity, and the policy
     assigns faces, not a type scale. The one exception is leading, below. */
  [dir="rtl"] .tpl,
  [dir="rtl"] .tpl * {
    font-family: "IBM Plex Sans Arabic", "Tajawal", sans-serif !important;
  }
  /* SECTION TITLES ARE SPLIT ACROSS THE CATALOGUE, 27 Tajawal / 22 Cairo.
     The written policy says both things and they cannot both be true of the
     same element:

       "Tajawal Bold ExtraBold for CV name headline AND SECTION TITLES
        inside CV template"
       "Word CV template styles ... Section Title CAIRO BOLD 12pt all caps"

     Asked which won, the answer was "50% Cairo, 50% Tajawal" - so the
     catalogue carries both, and the split follows each template's own Latin
     register rather than a coin toss. Two templates that look alike in
     English must not diverge in Arabic for no reason:

       grotesque Latin section heads (Archivo, Archivo Narrow)  -> Tajawal
       geometric / serif / humanist (Montserrat, Poppins, Anton,
         Fraunces, Merriweather, Inter, Open Sans, Source Sans,
         IBM Plex Mono)                                         -> Cairo

     That lands 27/22, which is as near even as a non-arbitrary rule gets.
     Measured, not guessed: Archivo leads the section heads in 25 of the 49.

     To collapse it back to one face, delete one of the two rules below - the
     Cairo rule is the default and the .cv-sections-taj rule is the override. */
  [dir="rtl"] .tpl .cv-section,
  [dir="rtl"] .tpl .cv-section * {
    font-family: "Cairo", "Tajawal", sans-serif !important;
  }
  /* Same specificity as the rule above (0,2,0), so SOURCE ORDER decides and
     this must stay after it. */
  [dir="rtl"] .cv-sections-taj .cv-section,
  [dir="rtl"] .cv-sections-taj .cv-section * {
    font-family: "Tajawal", "Cairo", sans-serif !important;
  }
  [dir="rtl"] .tpl .cv-name,
  [dir="rtl"] .tpl .cv-name * {
    font-family: "Tajawal", "Cairo", sans-serif !important;
    /* ExtraBold per the policy. Only raised where the template already set a
       bold-or-heavier name, so a deliberately light masthead is not shouted
       at; Tajawal has a real 800 and does not need synthesising. */
    font-weight: 800 !important;
  }
</style>"""


_DOC_TMPL = """<!DOCTYPE html>
<html lang="{lang}" dir="{dir}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
{fonts}
{rtl_css}{typography_head}
<style>
  html, body {{ margin: 0; padding: 0; background: #eef0f2; }}
  *, *::before, *::after {{ box-sizing: border-box; }}
  .tpl {{ background: #fff; margin: 0 auto; }}
  @media screen {{ .tpl {{ box-shadow: 0 8px 30px rgba(0,0,0,0.12); }} }}
  @page {{ size: 850px 1100px; margin: 0; }}
  @media print {{
    html, body {{ background: #fff; }}
    .tpl {{ box-shadow: none; }}
    * {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
  }}
</style>
</head>
<body>
{canvas}
{typography_body}{autofit}
</body>
</html>"""


def document_html(data: dict, template_key: str, *, title: str | None = None,
                  for_pdf: bool = False) -> str:
    """Full standalone HTML doc: the canvas + fonts + print CSS + auto-fit.

    `for_pdf` embeds the font bytes instead of linking them — required, because
    the PDF path has no base URL to resolve a relative font URL against.

    The auto-fit engine ships in every document and runs itself once the fonts
    have loaded, so the preview and the PDF paginate identically. Callers that
    need the outcome await `window.ResumeAutofit.ready`.
    """
    canvas = canvas_html(data, template_key)
    name = (data.get("name") or "Resume").strip()
    # The user's font choices (docs/CVSTAND_FONT_CONTROLS.md), VALIDATED -
    # never the raw keys. Both blocks are "" when nothing was chosen, and they
    # are concatenated rather than given lines of their own, so a résumé with
    # no typography keys emits byte-for-byte the document it always did.
    #
    # Not for the PDF yet: its fonts must be inlined (no base URL - see
    # font_head), which is step 4 of the spec. Until then an export keeps the
    # template's own faces rather than silently falling back.
    ty_head, ty_body = ("", "") if for_pdf else document_blocks(
        typography_of(data)[0], lang_of(data))
    # `dir` on <html> is what makes the whole document mirror: it is what the
    # logical CSS properties in the templates resolve against, and what the
    # RTL-scoped rules below select on. For lang="en" this emits dir="ltr",
    # which is the browser default — so English rendering is untouched.
    return _DOC_TMPL.format(
        title=title or f"{name} — {template_key}",
        lang=lang_of(data),
        dir=dir_of(data),
        fonts=font_head(for_pdf=for_pdf, lang=lang_of(data)),
        rtl_css=RTL_TYPOGRAPHY if dir_of(data) == "rtl" else "",
        typography_head=ty_head,
        canvas=canvas,
        typography_body=ty_body,
        autofit=autofit_script(),
    )
