"""DOCX export — docxtpl fills a Word master (.docx with Jinja2 tags) from the
same resume dict the HTML templates use.

Word has no CSS layout engine, so this is a PARALLEL template family, not a
render of the HTML. Each HTML template maps to one master via
`registry.Template.docx_master` — one per category, so 49 layouts collapse onto
2 Word documents. Since typography step 5 each download still carries its
own template's accent and fonts (or the user's chosen fonts): see
`docx_theme.py`. The documented divergences (rings -> dot glyphs, sidebar
folded into the main flow) live in
`word_masters/README.md`; the masters themselves are generated by
`tools/build_word_masters.py`.

Until a master .docx exists this raises DocxExportError with a clear message,
so the route can 501 rather than 500.
"""
from __future__ import annotations

import logging
from pathlib import Path

from .. import registry
from ..config import UPLOADS_DIR, WORD_MASTERS_DIR
from ..schema import DOT_TOTAL, dots_for, lang_of, normalize
from . import docx_design, docx_font_embed, docx_layout, docx_theme


log = logging.getLogger(__name__)


class DocxExportError(RuntimeError):
    pass


# The RTL counterpart of each master. A SEPARATE FILE, not a switch inside the
# LTR one: a .docx has no conditional layout, and the English masters are tuned
# to fit exactly one page - re-tuning them to also hold Arabic would put at risk
# the thing sessions 6 and 8 spent their time on.
#
# A missing RTL master RAISES rather than falling back to the English one. The
# fallback would produce a left-to-right Word file with English headings for an
# Arabic resume - output that is wrong rather than absent, which is the failure
# shape this project keeps finding. The route turns the error into a 501 that
# says what is missing.
_RTL_MASTERS = {
    "ats_standard.docx": "ats_standard_rtl.docx",
    "modern_editorial.docx": "modern_editorial_rtl.docx",
    "modern_layout.docx": "modern_layout_rtl.docx",
    "modern_gutter.docx": "modern_gutter_rtl.docx",
}


def _master_for(tpl, data: dict) -> str:
    """The master filename for this template AND this resume's language.

    A Modern template with a Word layout (docs/WORD_LAYOUTS_PLAN.md) uses the
    layout masters; every other template its category's master."""
    name = docx_layout.master_for(tpl.key) or tpl.docx_master
    if not name or lang_of(data) != "ar":
        return name
    rtl = _RTL_MASTERS.get(name)
    if not rtl:
        raise DocxExportError(
            f"No right-to-left Word master mapped for {name!r}. "
            f"Build one with: python tools/build_word_masters.py")
    return rtl


def _dot_glyphs(level: str) -> str:
    """Dot run for a level word, or "" when the word is off the scale.

    dots_for() returns 0 for anything unmapped and documents that as "renders as
    text only" — so an unmapped level must produce NO glyphs. Returning a full
    row of empty circles instead would put "English — Native ○○○○○" on the page,
    a graphic flatly contradicting the text beside it.
    """
    filled = dots_for(level)
    if not filled:
        return ""
    return "●" * filled + "○" * (DOT_TOTAL - filled)  # ● / ○


def _contact_items(contact: dict) -> list[str]:
    """The contact details one per line, for a template that stacks them."""
    bits = [contact.get(k, "") for k in ("email", "phone", "address", "site")]
    bits += [s.get("label", "") for s in contact.get("social", [])]
    return [b.strip() for b in bits if (b or "").strip()]


def _contact_line(contact: dict) -> str:
    """Word has no sidebar, so the contact block collapses to one pipe-separated
    line. Built here rather than in the master: Jinja inside a .docx cannot
    accumulate a list without leaving stray paragraphs behind."""
    bits = [contact.get(k, "") for k in ("email", "phone", "address", "site")]
    bits += [s.get("label", "") for s in contact.get("social", [])]
    return "  |  ".join(b.strip() for b in bits if (b or "").strip())


def _photo(doc, photo_url: str):
    """An InlineImage for the resume photo, or "" when there isn't a usable one.

    Returns a falsy value — not a placeholder — when the photo is missing or the
    file has been deleted, so the master's `{%p if photo %}` guard drops the
    whole paragraph instead of leaving a blank gap.

    Only the Modern master calls this. No ATS template has a photo slot (images
    defeat resume parsers), and the Word family mirrors that.
    """
    if not photo_url:
        return ""
    path = UPLOADS_DIR / Path(photo_url).name
    if not path.exists():
        return ""
    try:
        from docx.shared import Mm
        from docxtpl import InlineImage
        # 22mm, not larger: the Modern master is tuned so a resume WITH a photo
        # still fits one page. Enlarging this pushes the tail sections onto a
        # second page — re-run tools/build_word_masters.py --verify if changed.
        return InlineImage(doc, str(path), width=Mm(22))
    except Exception:  # noqa: BLE001 - a bad image must not fail the export
        return ""


def _context(data: dict, doc=None, template_key: str | None = None) -> dict:
    r = normalize(data)
    for sk in r.get("skills", []):
        sk["dot_glyphs"] = _dot_glyphs(sk.get("level", ""))
        sk["dots"] = dots_for(sk.get("level", ""))
    for lang in r.get("languages", []):
        lang["dot_glyphs"] = _dot_glyphs(lang.get("level", ""))
    r["contact_line"] = _contact_line(r.get("contact") or {})
    r["contact_items"] = _contact_items(r.get("contact") or {})
    layout = template_key is not None and docx_layout.spec_for(template_key) is not None
    if doc is None:
        photo = ""
    elif layout:
        photo = _layout_photo(doc, r.get("photo_url", ""), template_key, lang_of(data))
    else:
        photo = _photo(doc, r.get("photo_url", ""))
    ctx = {"r": r, "photo": photo}
    if layout:
        ctx["lay"] = docx_layout.context(r, template_key, lang_of(data), photo)
    return ctx


def _layout_photo(doc, photo_url: str, template_key: str, lang: str):
    """The photo at its template's size and shape (round where the PDF's is),
    or "" - the same guard as _photo."""
    if not photo_url:
        return ""
    path = UPLOADS_DIR / Path(photo_url).name
    if not path.exists():
        return ""
    try:
        return docx_layout.photo_image(doc, path, template_key, lang)
    except Exception:  # noqa: BLE001 - a bad image must not fail the export
        return ""


def render_docx(data: dict, template_key: str) -> bytes:
    tpl = registry.get(template_key)
    if tpl is None:
        raise DocxExportError(f"Unknown template {template_key!r}.")
    master_name = _master_for(tpl, data)
    if not master_name:
        raise DocxExportError(f"No Word master mapped for {template_key!r}.")

    master_path = WORD_MASTERS_DIR / master_name
    if not master_path.exists():
        raise DocxExportError(
            f"Word master {master_name!r} is not authored yet "
            f"(expected at {master_path}). DOCX export for {template_key} is pending."
        )

    if docx_design.has_design(template_key):
        # the template's own Word DESIGN, built in code (docs/WORD_FIDELITY_AUDIT.md)
        return _render_design(data, template_key)

    try:
        from docxtpl import DocxTemplate
    except ImportError as exc:  # pragma: no cover
        raise DocxExportError("docxtpl is not installed. Run: pip install docxtpl") from exc

    import io

    doc = DocxTemplate(str(master_path))
    # Context is built AFTER the template exists: an InlineImage has to be bound
    # to the document it will be embedded in.
    # autoescape is REQUIRED: without it docxtpl writes user text straight into
    # the document XML, so an "&" in a company name ("Halden & Row") is dropped
    # and "<" can corrupt the package.
    ctx = _context(data, doc, template_key)
    doc.render(ctx, autoescape=True)
    # The template's accent and fonts, or the user's chosen fonts (step 5):
    # rewrites the master's role styles, so it runs on the filled document.
    resolved = docx_theme.resolve(data, template_key)
    docx_theme.apply(doc.docx, resolved)
    if "lay" in ctx:
        # the template's SHAPE: columns, band, fills, zone colours (the plan)
        docx_layout.apply(doc.docx, template_key, lang_of(data), resolved, ctx["lay"])
    faces = docx_theme.faces_drawn(doc.docx, resolved)
    buf = io.BytesIO()
    doc.save(buf)
    # Step 6: the file carries the faces its text draws, so it looks the same
    # on a PC that has none of them installed (docx_font_embed.py).
    out = docx_font_embed.embed_fonts(buf.getvalue(), faces)
    log.info("docx %s: %d KB, %d embedded face(s) %s", template_key, len(out) // 1024,
             len(faces), sorted(faces))
    return out


def _photo_path(photo_url: str) -> Path | None:
    if not photo_url:
        return None
    path = UPLOADS_DIR / Path(photo_url).name
    return path if path.exists() else None


def _render_design(data: dict, template_key: str) -> bytes:
    import io

    doc, resolved = docx_design.render(data, template_key,
                                       _photo_path(normalize(data).get("photo_url", "")))
    faces = docx_design.faces_drawn(doc, resolved)
    buf = io.BytesIO()
    doc.save(buf)
    out = docx_font_embed.embed_fonts(buf.getvalue(), faces)
    log.info("docx %s (design): %d KB, %d embedded face(s)", template_key, len(out) // 1024,
             len(faces))
    return out
